### ISSUE TITLE
希望能手动修改日期

### ISSUE THREAD

**Issue by Felix2yu** [duxins/alog#16]
由于各种情况，有时候需要补记前一两天的日记。补记后时间线里当天的内容就会乱掉了，希望能够手动变更时间线里的日期。

**Comment by Felix2yu** [comment]
App Store里没有0.1.3，我用最新的0.2.0没有找到更改时间线的笔记日期的地方？

**Comment by duxins** [comment]
版本 0.1.3 没有发布，只把部分代码合并到了 0.2.0。由于**修改时间**功能还未经过充分的测试，计划将其放到下一个版本（预计将在本周末发布）。感谢理解与支持！ 🙏
