### ISSUE TITLE
[bug]出现语音无法识别的500错误

### ISSUE THREAD

**Issue by AeonWorks** [duxins/alog#41]
今天两条都识别文本报错，如下是其中一条的具体错误信息：

500. unmarshal_response_body_failed err :invalid character
'<' looking for beginning of value (request id:20240505072910994103194LGMEILX2)

版本：v0.2.2

**Comment by AeonWorks** [comment]
刚测试又好了。我没做任何其他操作。请问是不是语音识别不是在本地，而需要过服务器的？

**Comment by duxins** [comment]
你好，Whisper 语音转写需要调用 OpenAI API 接口，默认使用 Cloudflare Worker 做中转， 相关代码在：`Server/src/worker.js`。

可以换个网络环境再试试看。
