### ISSUE TITLE
恳请大佬更新，给出更多模型选项

### ISSUE THREAD

**Issue by yinghu183** [duxins/alog#44]
比如4o等等，或者能够自定义模型就更好了。voicenotes我也试用了，比这个臃肿了许多，而且界面也用不习惯。这个已经star&购买，再次恳请大佬闲暇时能够更新！

**Comment by duxins** [comment]
你好，感谢支持！v0.2.4 **自定义服务器** 支持指定 4o 模型，已经提交审核。
