### ISSUE TITLE
这几天在香港使用App自带的whisper会403，使用自定义服务器的时候，

### ISSUE THREAD

**Issue by new4u** [duxins/alog#50]
使用自定义服务器的时候，选择的whisper会是用自定义服务器的token吗?

发现token消耗很快，所以问一下谢谢

**Comment by duxins** [comment]
你好！ Whisper 转写和总结都会使用自定义服务器。

可以登录 https://platform.openai.com/usage 查看 api 使用情况。

**Comment by new4u** [comment]
默认的服务是宕机了吗？
为什么总是403报错呢

**Comment by duxins** [comment]
香港现在用不了 OpenAI API 👇

[OpenAI宣布下月起不支援地區將停用API服務](https://hk.finance.yahoo.com/news/財經-openai宣布下月起不支援地區將停用api服務-023006639.html?guccounter=1)

可以使用其它国家的代理绕过封锁。

**Comment by KevinSpringer1** [comment]
> 香港现在用不了 OpenAI API 👇
> 
> [OpenAI宣布下月起不支援地區將停用API服務](https://hk.finance.yahoo.com/news/%E8%B2%A1%E7%B6%93-openai%E5%AE%A3%E5%B8%83%E4%B8%8B%E6%9C%88%E8%B5%B7%E4%B8%8D%E6%94%AF%E6%8F%B4%E5%9C%B0%E5%8D%80%E5%B0%87%E5%81%9C%E7%94%A8api%E6%9C%8D%E5%8B%99-023006639.html?guccounter=1)
> 
> 可以使用其它国家的代理绕过封锁。

请问用的时候是直接从自己手机用作者大大的key调用的官方api吗

**Comment by duxins** [comment]
不是从手机直接调用。使用 Cloudflare Workers 做了中转，域名是 api.alog.tarbotech.com。

服务端代码： 
https://github.com/duxins/alog/blob/release/v0.2.5/Server/src/worker.js

**Comment by new4u** [comment]
这需要自己修改修改代码，还是已经在更新了版本里了？

**Comment by duxins** [comment]
不需要修改代码。

上面那个域名在香港用不了，可以用其它国家的 VPN 或者代理试一下。

**Comment by new4u** [comment]
好的谢谢
