### ISSUE TITLE
Apple Watch上录制音频，没有办法自动同步到手机

### ISSUE THREAD

**Issue by new4u** [duxins/alog#52]
iOS版本18.1 Apple Watch发现在Apple Watch上录制音频，没有办法自动同步到手机，不知道之前改了手机的区域还是语言，然后现在全部改回来还不行，重启了手机和手表也都没有办法同步语音

**Comment by duxins** [comment]
感谢反馈！能否告知一下 watchOS 的版本？

**Comment by new4u** [comment]
谢谢，突然发现自动好了
