### ISSUE TITLE
这两天转写显示“bad response”，转写不了

### ISSUE THREAD

**Issue by alanjustalan** [duxins/alog#8]
是出了什么问题吗？

**Comment by duxins** [comment]
用的是 App 默认服务器吗？

**Comment by duxins** [comment]
我这里默认服务器转写功能目前是正常的，我稍后确认下是不是域名被墙了。

如果是自定义服务器的话，建议使用其他 ChatGPT 客户端检查一下 Whisper 是否可用。

**Comment by alanjustalan** [comment]
我这边用默认服务器的话就没问题。Whisper 转写需要用到服务器的吗？我以为转写是纯本地模型的，总结才用到gpt。
“使用其他 ChatGPT 客户端检查一下 Whisper 是否可用”想知道有哪些ChatGPT 客户端可以检查一下 Whisper 是否可用，能推荐下吗？

**Comment by duxins** [comment]
是的，Whisper 也需要用到服务器。本地模型太大了，手机跑着也费劲。

OpenCat 最新版支持 Whisper，你可以试一下。

**Comment by duxins** [comment]
根据上面错误信息，估计是你的中转服务器不支持 Whisper。 

如果你能修改中转服务器代码的话， 可以参考下面这个提交，只需要对 `Content-Type` 是 `multipart/form-data` 的请求做下简单转发即可

https://github.com/barretlee/cloudflare-proxy/commit/1172395ba46c87eebace82ecfc212c4bf71c1dd2

**Comment by duxins** [comment]
麻烦更新到最新版 v0.0.5，验证自定义服务器时会检查是否支持 Whisper
